#!/bin/bash

SVC_PORT=80
LOCAL_PORT=3333
NAMESPACE=mon

echo '------------------------------------'
echo 'Credentials:'
echo ''
echo -n 'user: '
kubectl get secrets prometheus-grafana -n mon -o jsonpath={".data.admin-user"} | base64 -d
echo ''
echo -n 'password: '
kubectl get secrets prometheus-grafana -n mon -o jsonpath={".data.admin-password"} | base64 -d
echo ''
echo ''
echo "Service available : <http://127.0.0.1:${LOCAL_PORT}>"
echo ''
echo '------------------------------------'

kubectl port-forward -n ${NAMESPACE} svc/prometheus-grafana ${LOCAL_PORT}:${SVC_PORT}
